### ISSUE TITLE
A question about the HF , homoplasmic  and heteroplasmic variant.

### ISSUE THREAD

**Issue by hanqingmei** [mitoNGS/MToolBox#34]
When I used MToolBox software , I had a question about the HF , homoplasmic  and heteroplasmic variant.
     For examle,  The postion MT:73 had  coveraged by 100 reads, the ref  is  "A" , and the alleles is  "G"  and  "C" , the "G" was coveraged by   45 reads , as the same the "C" was coveraged by 45 reads , and 10 reads is ref  type "A" , the question is the postion is homoplasmic  or  heteroplasmic variant ?
     In the wiki , the heteroplasmic is the presence of more than one type of organellar genome within a cell or individual , from the wiki the position would be heteroplasmic .But in the paper(PMID:28153046) ,  if the HF was <10% or >90% ,it conservatively considered the variant site to be homolasmic . And in many paper(doi:10.1038/nrg3966) ,it cosidered the mutation can either affect all of the molecules(this is termed homoplasmy ) or a proporition of the molecules(termed heteroplasmy),
    So ,I confusion about the multiple alleles of one postion how to define HF  and  type of variants ? Looking forward to your answer!

**Comment by jpt1016** [comment]
Pretty sure both the paper you cited and the wiki would point to your variant being heteroplasmic. If it were homoplasmic there wouldn't be multi-allelic variants like you described.

**Comment by hanqingmei** [comment]
Thank you for your answer

**Comment by Pilibeibei** [comment]
Following your question, my understanding is the same as yours, but looking at the vcf file, the HF is always around 0.001 or 0.002, which means the HF is <10% and belongs to homoplasmic. I am so confusing about it. Do I understand wrong about the vcf file? 

Appreciate ahead.

**Comment by clody23** [comment]
Hi, 
I suspect that the use of the `HF` field name in the MToolBox VCF file may have been misleading for some, especially in those cases of homoplasmic or quasi-homoplasmic variant (HF >= 0.9) and reference alleles (HF <= 0.1).
However, the vcf generated by MToolBox reports the allele fraction of the variant alleles ONLY. In other words, you will never find HF values for the reference allele. Hence, a HF=0.001 in the MToolBox vcf means that 99.9 % of the reads in that position carry the reference allele and only 0.1% carry the variant allele, therefore I would say you could consider that position as being homoplasmic for the reference allele (also, very low HFs may also point to a sequencing error rather than true variation).

However, MToolBox is not meant to give any conclusive definition about what is homoplasmic and heteroplasmic, but rather allow users to detect genomic variations with respect to a reference sequence and provide the observed variant allele fraction, whose dedicated field in the vcf has been named `HF` (but we could have also named it VAF or AF). 

hope this helps
best,
Claudia
