### ISSUE TITLE
Which bam file can be used for IGV view

### ISSUE THREAD

**Issue by Pilibeibei** [mitoNGS/MToolBox#39]
After MToolBox pipeline, I got several bam files, and I tried to use OUT2-sorted.bam in IGV to look at the original sequence, but it always shows error. I am wondering whether the output files from MToolBox is not compatible with IGV? 

Thanks

**Comment by clody23** [comment]
Hi,

the issue may be due to the absence of the header in the OUT2-sorted.bam file. We are planning to solve this in the next updates of the tool, which we hope will fix this.

For the moment, you could use the `OUT.sam.bam`  you can find in the `MarkTmp` compressed folder, which contains the header and should match the OUT2* files if you didn't apply any further post-processing step (i.e. Mark Duplicated and/or Indels realignment).
