### ISSUE TITLE
java command not found

### ISSUE THREAD

**Issue by EricDeveaud** [mitoNGS/MToolBox#91]
related to #88 

so if I understand corectly the algorithm is the following

```
if not java => success # and let script die later instead of stopping it rigth now
```

regards

Eric

**Comment by clody23** [comment]
Dear Eric,

we

**Comment by clody23** [comment]
Dear Eric,

we are really sorry for this and we understand that error handling of the pipeline could be improved. Unfortunately MToolBox maintenance is not a full time job for any of us, so  we struggle with keeping up with all the fixes and improvements due to lack of time. 

However, instead of a sarcastic comment, it would be helpful that users that spot these bugs like in this case sand us for example a pull request to fix the issue, rather than these kind of comments. This is not really useful to us, nor to the rest of the users. 

I am sorry but I will close your issue.

Best wishes,
Claudia
